services:
  - type: web
    name: registro-de-protocolos
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    plan: free
    region: oregon
